### ISSUE TITLE
hola tengo error

### ISSUE THREAD

**Issue by 13adahan** [Gilbert097/Snapchat-Clone-IOS#1]
hola yo no hablo muy bien español podemos hablar english?

there are errors in the app. after registration you have to login again, it does not send you automatically. and it cannot find other users for sending snaps.

**Comment by Gilbert097** [comment]
Hi  @13adahan ,

For the application to work, it is necessary to configure the _**GoogleService-Info.plist**_ file in the project.

It is through this file that the application will be able to consume Firebase resources.

To get this file, just create an IOS project on [Firebase](https://console.firebase.google.com/).

Here are some images to help:

![Screen Shot 2022-05-15 at 14 05 28](https://user-images.githubusercontent.com/49564882/168485139-8b8cd7fa-7345-47fe-8e59-b5e22bdaa3ad.png)


Having successfully configured the project, to be able to send snaps it is necessary to register at least 2 users!

Hope this helps!
